version: '3.9'

services:
  angular_signals:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: angular-signals
    volumes:
      - ~/.ssh:/workspace/.ssh:cached
      - ../:/workspace/Web
    ports:
      - "4200:4200"
    working_dir: /workspace/Web
    stdin_open: true
    tty: true
